---
name: torrust
services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./storage/proxy/webroot:/var/www/html
      - ./storage/certbot/etc:/etc/letsencrypt
      - ./storage/certbot/lib:/var/lib/letsencrypt
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - proxy

  proxy:
    image: nginx:mainline-alpine
    container_name: proxy
    restart: unless-stopped
    networks:
      - frontend_network
      - backend_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./storage/proxy/webroot:/var/www/html
      - ./storage/proxy/etc/nginx-conf:/etc/nginx/conf.d
      - ./storage/certbot/etc:/etc/letsencrypt
      - ./storage/certbot/lib:/var/lib/letsencrypt
      - ./storage/dhparam:/etc/ssl/certs
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - index-gui
      - index
      - tracker

  index-gui:
    image: torrust/index-gui:develop
    container_name: index-gui
    tty: true
    restart: unless-stopped
    environment:
      - USER_ID=${USER_ID}
      - NUXT_PUBLIC_API_BASE=${TORRUST_INDEX_GUI_API_BASE_URL:-http://localhost:3001/v1}
      - NITRO_HOST=${NITRO_HOST:-0.0.0.0}
      - NITRO_PORT=${NITRO_PORT:-3000}
    networks:
      - frontend_network
    ports:
      - 3000:3000
    volumes:
      - ./storage/index-gui/log:/var/log/torrust/index-gui:Z
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - index
      - tracker

  index:
    image: torrust/index:develop
    container_name: index
    tty: true
    restart: unless-stopped
    environment:
      - USER_ID=${USER_ID}
      - TORRUST_INDEX_DATABASE=${TORRUST_INDEX_DATABASE:-sqlite3}
      - TORRUST_INDEX_DATABASE_DRIVER=${TORRUST_INDEX_DATABASE_DRIVER:-sqlite3}
      - TORRUST_INDEX_CONFIG_OVERRIDE_TRACKER__TOKEN=${TORRUST_INDEX_CONFIG_OVERRIDE_TRACKER__TOKEN:-MyAccessToken}
      - TORRUST_INDEX_CONFIG_OVERRIDE_AUTH__SECRET_KEY=${TORRUST_INDEX_CONFIG_OVERRIDE_AUTH__SECRET_KEY:-MaxVerstappenWC2021}
      - TORRUST_INDEX_API_CORS_PERMISSIVE=${TORRUST_INDEX_API_CORS_PERMISSIVE:-true}
    networks:
      - backend_network
    ports:
      - 3001:3001
    volumes:
      - ./storage/index/lib:/var/lib/torrust/index:Z
      - ./storage/index/log:/var/log/torrust/index:Z
      - ./storage/index/etc:/etc/torrust/index:Z
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - tracker

  tracker:
    image: torrust/tracker:develop
    container_name: tracker
    tty: true
    restart: unless-stopped
    environment:
      - USER_ID=${USER_ID}
      - TORRUST_TRACKER_DATABASE=${TORRUST_TRACKER_DATABASE:-sqlite3}
      - TORRUST_TRACKER_CONFIG_OVERRIDE_CORE__DATABASE__DRIVER=${TORRUST_TRACKER_CONFIG_OVERRIDE_CORE__DATABASE__DRIVER:-Sqlite3}
      - TORRUST_TRACKER_CONFIG_OVERRIDE_HTTP_API__ACCESS_TOKENS__ADMIN=${TORRUST_TRACKER_CONFIG_OVERRIDE_HTTP_API__ACCESS_TOKENS__ADMIN:-MyAccessToken}
    networks:
      - backend_network
    ports:
      - 6969:6969/udp
      - 7070:7070
      - 1212:1212
    volumes:
      - ./storage/tracker/lib:/var/lib/torrust/tracker:Z
      - ./storage/tracker/log:/var/log/torrust/tracker:Z
      - ./storage/tracker/etc:/etc/torrust/tracker:Z
    logging:
      options:
        max-size: "10m"
        max-file: "10"

networks:
  frontend_network: {}
  backend_network: {}

volumes:
  mysql_data: {}
